[".vim_runtime"]
  type = "git-repo"
  url = "https://github.com/amix/vimrc.git"
  clone.args = ["--depth=1"]

[".intellimacs"]
  type = "git-repo"
  url = "https://github.com/MarcoIeni/intellimacs.git"

[".config/wezterm"]
  type = "git-repo"
  url = "https://github.com/pro470/wezterm-config.git"

["unmanaged_executable/zen.installer.exe"]
  type = "file"
  url = "https://github.com/zen-browser/desktop/releases/download/{{(output "cmd" "/C" "pwsh -Command" "cmd" "/C"  "curl --silent 'https://api.github.com/repos/zen-browser/desktop/releases/latest' | jq -r '.tag_name'")}}/zen.installer.exe"
  executable = true
  refreshPeriod = "24"

["unmanaged_executable/Spacedrive-windows-x86_64.msi"]
  type = "file"
  url = "https://github.com/spacedriveapp/spacedrive/releases/download/{{(output "cmd" "/C" "curl --silent 'https://api.github.com/repos/spacedriveapp/spacedrive/releases/latest' | jq -r '.tag_name'")}}/Spacedrive-windows-x86_64.msi"
  executable = true
  refreshPeriod = "24"

["unmanaged_executable/windows_cursor"]
  type = "archive"
  url = "https://github.com/ful1e5/Bibata_Cursor/releases/download/{{(output "cmd" "/C" "curl --silent 'https://api.github.com/repos/ful1e5/Bibata_Cursor/releases/latest' | jq -r '.tag_name'")}}/Bibata-Modern-Classic-Windows.zip"
  refreshPeriod = "24"


